server:
  port: 80

eureka:
  client:
    register-with-eureka: false #表示是否将自己注册到EurekaServer
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka

ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000

feign:
  hystrix:
    enabled: true